# Iteration 15 eval: SWA of iter12 checkpoints {400,500,558} -- the reliability cross-check for
# iter14 (SWA of iter11). If BOTH SWA models pass imm reliably, SWA tames d=32 variance -> 13.2x.
FILE_AHEAD = "RWKV-iter15"
FILE_IMM = "RWKV-P-iter15"

MODEL_PATH = "pretrain/rwkv/opt_iter15/rwkv_iter15_swa.pth"
DEVICE = "cuda"
DTYPE = "bfloat16"

DATASET_LMDB_PATH = "test_db"
DATASET_LMDB_SIZE = 8_000_000_000
LABEL_FILTER_LMDB_PATH = "label_filter_db"
LABEL_FILTER_LMDB_SIZE = 1_000_000_000

RAW = false
RAW_DB_PATH = "raw/result_db"
RAW_DB_SIZE = 1_000_000_000

USER_START = 101
USER_END = 200

NUM_FETCH_PROCESSES = 7
