# Iteration 24 eval: d=64 iter16 arch, EVEN LONGER 6-epoch decay. Output = rwkv_iter24_186.pth.
FILE_AHEAD = "RWKV-iter24"
FILE_IMM = "RWKV-P-iter24"

MODEL_PATH = "pretrain/rwkv/opt_iter24/rwkv_iter24_186.pth"
DEVICE = "cuda"
DTYPE = "bfloat16"

DATASET_LMDB_PATH = "test_db"
DATASET_LMDB_SIZE = 8_000_000_000
LABEL_FILTER_LMDB_PATH = "label_filter_db"
LABEL_FILTER_LMDB_SIZE = 1_000_000_000

RAW = false
RAW_DB_PATH = "raw/result_db"
RAW_DB_SIZE = 1_000_000_000

USER_START = 101
USER_END = 200

NUM_FETCH_PROCESSES = 7
